### ISSUE TITLE
snowrider3d macOS

### ISSUE THREAD

**Issue by dlcasto3** [wraithcode2050/wraithcode2050.github.io#2]
TypeJsError: null is not an object (evaluating 'str.length'

**Comment by dlcasto3** [comment]
An error occurred running the Unity content on this page. The error was:
TypeError: null is not an object (evaluating 'str.length')

**Comment by wraithcode45** [comment]
what are you doing...

**Comment by dlcasto3** [comment]
I was on snowrider3d and I got that error on macOS

**Comment by wraithcode45** [comment]
sounds like a skill issue tbh :/
