### ISSUE TITLE
Cross-site Scripting (XSS) issue not resolved

### ISSUE THREAD

**Issue by dlcasto3** [wraithcode2050/wraithcode2050.github.io#3]
innerHTML

Unsanitized input from data from a remote resource flows into innerHTML, where it is used to dynamically construct the HTML page on client side. This may result in a DOM Based Cross-Site Scripting attack (DOMXSS).

line:225

[‎tools/ytwa/originalshh.js]

**Comment by wraithcode45** [comment]
womp womp im doing it that way to completely obfuscate it so tech doesnt know how it works
